# Generated by Django 3.1.2 on 2020-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actor biography')),
                ('country', models.CharField(max_length=100, verbose_name='Actor country')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Film Title')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Film description')),
                ('full_hd', models.BooleanField(default=True)),
                ('year', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
                ('lasting', models.CharField(max_length=10)),
                ('actors', models.ManyToManyField(blank=True, null=True, to='mainapp.Actor', verbose_name='Actors')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('films', models.ManyToManyField(blank=True, null=True, to='mainapp.Film', verbose_name='Films')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Category slug')),
                ('films', models.ManyToManyField(blank=True, null=True, to='mainapp.Film', verbose_name='Films')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Film', verbose_name='Films'),
        ),
    ]
