# Generated by Django 3.1.2 on 2020-10-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='first_name',
            field=models.CharField(default='Max', max_length=255),
        ),
        migrations.AddField(
            model_name='actor',
            name='second_name',
            field=models.CharField(default='Brance', max_length=255),
        ),
    ]
