# Generated by Django 3.1.2 on 2020-11-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201030_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='Category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Country',
            new_name='countries',
        ),
    ]
