# Generated by Django 3.1.2 on 2020-11-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201101_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='constraints',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Constraints'),
        ),
    ]
