# Generated by Django 3.1.2 on 2020-11-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_film_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
