# Generated by Django 3.1.2 on 2020-11-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201102_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
    ]
