# Generated by Django 3.1 on 2020-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_film_is_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='lasting',
            field=models.CharField(max_length=30),
        ),
    ]
