# Generated by Django 3.1 on 2020-11-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201112_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='1', unique=True, verbose_name='Country slug'),
        ),
    ]
